/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    CardSection: typeof import('./src/components/CardSection.vue')['default']
    Column: typeof import('primevue/column')['default']
    ColumnGroup: typeof import('primevue/columngroup')['default']
    copy: typeof import('./src/components/DataTableScanStock copy.vue')['default']
    Data: typeof import('./src/components/Data.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataTableCheckStock: typeof import('./src/components/DataTableCheckStock.vue')['default']
    DataTableDeleteRFID: typeof import('./src/components/DataTableDeleteRFID.vue')['default']
    DataTableRegister: typeof import('./src/components/DataTableRegister.vue')['default']
    DataTableScanStock: typeof import('./src/components/DataTableScanStock.vue')['default']
    DataTableShopifySale: typeof import('./src/components/DataTableShopifySale.vue')['default']
    DataTableWarehouseStock: typeof import('./src/components/DataTableWarehouseStock.vue')['default']
    DataView: typeof import('./src/components/DataView.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('primevue/row')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SignalR: typeof import('./src/components/SignalR.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    Tag: typeof import('primevue/tag')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
  }
}
