/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    CardSection: typeof import('./src/components/CardSection.vue')['default']
    Column: typeof import('primevue/column')['default']
    copy: typeof import('./src/components/DataTableScanStock copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataTableCheckStock: typeof import('./src/components/DataTableCheckStock.vue')['default']
    DataTableRegister: typeof import('./src/components/DataTableRegister.vue')['default']
    DataTableScanStock: typeof import('./src/components/DataTableScanStock.vue')['default']
    DataView: typeof import('./src/components/DataView.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SignalR: typeof import('./src/components/SignalR.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
  }
}
