export interface PODescType {
  poNo: string;
  poDate?: Date | null;
  prNo?: string | null;
  companyCode?: string | null;
  poType?: number | null;
  confirmPO: boolean;
  approvePO: boolean;
  approvePO_Date?: Date | null;
  closeStatus: boolean;
  closeBy?: string | null;
  closeDate?: Date | null;
  cancelStatus: boolean;
  cancelBy?: string | null;
  cancelDate?: Date | null;
  shipMode?: string | null;
  paymentType?: string | null;
  termDay?: number | null;
  paymentDetail?: string | null;
  paymentTerm?: string | null;
  termDetail?: string | null;
  currency?: string | null;
  rates?: number | null;
  poDesc?: string | null;
  poRemark?: string | null;
  vendorId?: string | null;
  dlvCode?: string | null;
  userCreate?: string | null;
  createDate?: Date | null;
  userEdit?: string | null;
  editDate?: Date | null;
  needDate?: Date | null;
  etd?: Date | null;
  eta?: Date | null;
  finalETA?: Date | null;
  stepType?: string | null;
  previousStep?: number | null;
  currentStep?: number | null;
  approveTime?: number | null;
  poNetAmount?: number | null;
  poAmountBeforeVat?: number | null;
  poTotalAmount?: number | null;
}

export interface PODetailType {
  prNo: string;
  itemNo?: number | null;
  dlvCode?: string | null;
  customerPO?: string | null;
  sizeId?: number | null;
  size?: string | null;
  poNo?: string | null;
  orderNo?: string | null;
  itemId?: string | null;
  itemDesc?: string | null;
  itemCode?: string | null;
  colorCode?: string | null;
  prQty?: number | null;
  poQty?: number | null;
  uom?: string | null;
  unitPrice?: number | null;
  priceCurrency?: string | null;
  needDate?: Date | null;
  finalETA?: Date | null;
  orderCfmNo?: string | null;
  lastUpdateETA?: Date | null;
  lastSupComment?: string | null;
  receiveQty?: number | null;
  lastReceive?: Date | null;
  vendorId?: string | null;
  supplierDetail?: string | null;
  itemRemark?: string | null;
  chargeDetail?: string | null;
  chargeType?: string | null;
  chargeValueType?: string | null;
  chargeValue?: number | null; // decimal → number
  itemAmount?: number | null;
  itemNetAmount?: number | null;
}
